// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Users.Domain;

namespace Users.Domain.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Users.Domain.Models.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("215afa03-b189-4495-a7be-a88b7e5eb8c5"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("e99327fd-0911-48dc-b668-ec6edb966431"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("39c92b76-86d0-462e-9d72-83a72aff92e5"),
                            Name = ".Net"
                        },
                        new
                        {
                            Id = new Guid("a384ce15-423c-4c79-ae02-9e98e144148f"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("1407a7e3-dbaa-4543-a2c5-5f0d4872aef4"),
                            Name = "Unity"
                        },
                        new
                        {
                            Id = new Guid("c29ed288-a07e-4f08-9d64-fc7523104c25"),
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("1493ac2e-f113-4b55-aa23-84224da81bec"),
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("4c42b797-c133-4951-be60-e36a87d09654"),
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("686b6807-e575-4046-9137-7968156781a8"),
                            Name = "Vue"
                        },
                        new
                        {
                            Id = new Guid("7deff3f1-9c61-4ed4-9662-17ddb8389551"),
                            Name = "Express"
                        },
                        new
                        {
                            Id = new Guid("e673bd68-55c9-4db0-b4f7-f71d4648a9be"),
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("29a0bea2-67d4-4037-829e-32a5d6faccbf"),
                            Name = "MongoDb"
                        },
                        new
                        {
                            Id = new Guid("275152a0-0dbe-418d-aa1c-c69b5d72318e"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("b19dd1a2-697b-4795-bb48-e9769a80f483"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("6a9f552d-02dc-436b-9721-e03f8c8fd56c"),
                            Name = "C"
                        });
                });

            modelBuilder.Entity("Users.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Users.Domain.Models.UserTechnology", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("UserTechnologies");
                });

            modelBuilder.Entity("Users.Domain.Models.UserTechnology", b =>
                {
                    b.HasOne("Users.Domain.Models.Technology", "Technology")
                        .WithMany("UserTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Users.Domain.Models.User", "User")
                        .WithMany("UserTechnologies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
